### ISSUE TITLE
Offerta tasdiqlanganligini tekshirish

### ISSUE THREAD

**Issue by GxSupport** [GxSupport/boonApp#13]
Nima qilish kerak?
Bosh sahifaga kirilganda {{url}}/client/get ga so'rov yuboriladi va `phone_verified_at` null emasligiga tekshiriladi agarda ma'lumot mavjud bo'lsa keyingi apilarga so'rov jo'natiladi agarda null bo'lsa `Mijoz offertani tasdiqlash oynasi` #12 ga o'tkazib yuborish lozim.

**Comment by abduvali0320** [comment]
close #13
