### ISSUE TITLE
Bosh sahifadagi o'zgarishlar

### ISSUE THREAD

**Issue by GxSupport** [GxSupport/boonApp#14]
Nima qilish kerak?
1. Cheklangan miqdor so'zini `Ajratilgan limit` ga o'zgartirish va textni o'rtaga o'tkazish lozim FontSize: +2 qilish kerak
2. keyingi qatorda `limit` masalan 5 126 442 UZS `month` Masalan: 12 oyga yozuviga o'zgartirish lozim: Misol: 5 126 442 UZS 12 oyga
3. bosh sahifaga kirganda guidFinProduct dagi ID limit_list->data dagi guidFinProduct ga tengi avtomatik tanlangan turishi lozim.
3. Progressdagi Ishlatilgan summaga products massivdagi `sale_price` larni barchasini qo'shib chiqarish lozim. 
4. Sarflash mumkin so'zini Limit  ga o'zgartirish lozim summasi tanlangan limitdagi `limit` ni qo'yish lozim
5. Oldin skanerlangan so'zini `Tanlanganlar` ga o'zgartirish lozim
6.  tovar so'zini mahsulot ga o'zgartirish lozim

**Comment by abduvali0320** [comment]
close() #14
