### ISSUE TITLE
Skaner qilingan tovarlar

### ISSUE THREAD

**Issue by GxSupport** [GxSupport/boonApp#15]
Nima qilish kerak
1. Tovar skaner qilingandan so'ng skaner qilingan ma'lumotni  {{url}}/application/product_parse apiga jo'natish lozim va status 200 qaytgan holatda bosh sahifaga yo'naltirish lozim
2. Tovar haqida ma'lumot ko'rish oynasini qaytadan ko'rib chiqish lozim

**Comment by abduvali0320** [comment]
close() #15
